### ISSUE TITLE
Unhandled Rejection (Error): Cannot create styled-component for component: [object Object]

### ISSUE THREAD

**Issue by mozgbrasil** [Hermanya/react-landing-page#1]
Hello good afternoon

Can you help me

See error as images

The error occurs when using

import {Hero, CallToAction, ScrollDownIndicator} from 'react-landing-page'

![captura de tela de 2018-10-19 22-37-01](https://user-images.githubusercontent.com/17202780/47249878-d5a7f980-d3ef-11e8-961d-a9e14c2210d2.png)
![captura de tela de 2018-10-19 22-37-17](https://user-images.githubusercontent.com/17202780/47249879-d5a7f980-d3ef-11e8-9402-a688277f431d.png)

**Comment by Hermanya** [comment]
This error is quite bizarre. Maybe it has to do with the version of styled-components. If not then maybe Babel configuration.

**Comment by Hermanya** [comment]
How is your package Jon different from https://github.com/Hermanya/react-landing-page/blob/master/examples/sandbox/package.json ?

**Comment by mozgbrasil** [comment]
Hello good Morning

Note that the example repository displays some errors

![captura de tela de 2018-10-22 11-41-46](https://user-images.githubusercontent.com/17202780/47299662-263a7500-d5f1-11e8-983a-865f40c31fbd.png)
![captura de tela de 2018-10-22 11-41-47](https://user-images.githubusercontent.com/17202780/47299663-263a7500-d5f1-11e8-929f-49dbae43fb1d.png)
![captura de tela de 2018-10-22 11-42-12](https://user-images.githubusercontent.com/17202780/47299665-263a7500-d5f1-11e8-8c91-4301a9634a81.png)

**Comment by Hermanya** [comment]
Thank you for steps to reproduce the issue. Sorry for a late reply. I currently swamped with work. I'll try to get back to this towards the end of the week.

**Comment by Hermanya** [comment]
Regarding the errors in the example repo, they are somewhat minor, I just couldn't get around to fix these warnings.

**Comment by voordev** [comment]
@mozgbrasil 
Did you ever get this repo working?
If so could you please tell how and what was needed to get it working again? 
Kind regards

**Comment by mozgbrasil** [comment]
Good Morning

I do not have this feature working!

At the time I was studying and I found this component and I decided to test only

**Comment by Hermanya** [comment]
this ui lib is deprecated
