### ISSUE TITLE
Sandbox code is broken

### ISSUE THREAD

**Issue by stefanhayden** [Hermanya/react-landing-page#2]
`styled-components` is a missing dependency. codesandbox.io lets me add it in with one click but once it does load it the visual doesn't seem to match the code as the heading, subheading, and call to action are missing.

**Comment by Hermanya** [comment]
It seems like rebass did not age well. The version I have does not work with latest `styled-components` and the latest version has dropped most of the components available in the older version. That's a shame.

**Comment by voordev** [comment]
hi @Hermanya 
Understanding from your comment this repo is no longer usable?
Do you plan to update it or could you provide some instructions on how to make this work -again?
I have been unable to get this working so far.

Kind regards

**Comment by Hermanya** [comment]
@voordev it's not usable with latest versions of dependencies. I have a plan to update it, but lately, I have not had much time.

**Comment by ck-kc** [comment]
Hi @Hermanya could you summarise the changes that are needed to get this repo to work again? Would really like to get your module to work!

**Comment by Hermanya** [comment]
I think the most difficult part is updating Rebass, because they removed a lot of apis this project depends on. Honestly, it might be easier to rewrite this project from scratch.

**Comment by Hermanya** [comment]
this ui lib is deprecated
