### ISSUE TITLE
Attempted import error: 'Provider' is not exported from 'rebass'.

### ISSUE THREAD

**Issue by MrBandaruk** [Hermanya/react-landing-page#4]
I've use `create-react-app` to init my app. Then I added `react-landing-page` and `rebase`. Here is my App.js code:

```javascript
import React from 'react'
import { Provider, Heading, Subhead } from 'rebass'
import {
  Hero, CallToAction, ScrollDownIndicator
} from 'react-landing-page'

const App = props => (
  <Provider>
    <Hero
      color="black"
      bg="white"
      backgroundImage="https://source.unsplash.com/jxaj-UrzQbc/1600x900"
    >
        <Heading>Name of your app</Heading>
        <Subhead>a couple more words</Subhead>
        <CallToAction href="/getting-started" mt={3}>Get Started</CallToAction>
        <ScrollDownIndicator/>
    </Hero>
  </Provider>
)

export default App;
```

I get this error:
`Attempted import error: 'Provider' is not exported from 'rebass'.`

**Comment by Hermanya** [comment]
`Rebass` has changed a lot since I created this project. To make it work, you need `rebass@^2.0.0`.

I've been meaning to migrate this to latest `styled-components` and ditch `rebass`, but I have not had the time.

**Comment by MrBandaruk** [comment]
Thank you for the answer
