### ISSUE TITLE
Attempted import error: 'Provider' is not exported from 'rebass'.

### ISSUE THREAD

**Issue by moyid** [Hermanya/react-landing-page#5]
This seems to be out of date. Provider is no longer a component of rebass. Neither is Subhead.

**Comment by robertsami** [comment]
had the same issue. in case its helpful to others a work-around is to install the version of rebass from the sandbox example in this repo. i added the following to my package.json:
```
dependencies: {
...
    "rebass": "^2.1.0",
    "styled-components": "^3.0.0",
...
}
```

**Comment by Hermanya** [comment]
this ui lib is deprecated
